
liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [280, 200]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [650, 430]
                    mode: outbound

